// = Quick test infrastructure using GitLab + Jenkins in Docker - fack, no! Gitlab don't wanna work in my compose...
= Quick test infrastructure using Go Git server (GoGS) + Jenkins all in Docker

.prepare OS:
[source,bash]
----
echo "postgres.daggerok.com 127.0.0.1" >> /etc/hosts
echo "gogs.daggerok.com 127.0.0.1"     >> /etc/hosts
echo "jenkins.daggerok.com 127.0.0.1"  >> /etc/hosts
----

.prepare docker-conpose file:
[source,yaml]
----
version: '2.1'

services:

  postgres:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_DB: gogs
      POSTGRES_USER: gogs
      POSTGRES_PASSWORD: gogs
    ports: ['15432:5432']
    volumes: ['postgres:/var/lib/postgresql/data']
    networks:
      main:
        aliases: ['postgres.daggerok.com']
    restart: always

  gogs:
    image: 'gogs/gogs:0.11.43'
    ports:
      - '10022:22'
      - '13000:3000'
    volumes:
      - 'gogs:/var/gogs/git'
      - 'gogs:/var/gogs/ssh'
      - 'gogs:/var/gogs/gogs'
    links:
      - 'postgres:postgres'
    networks:
      main:
        aliases: ['gogs.daggerok.com']
    restart: always

  jenkins:
    image: 'jenkins/jenkins:2.125-alpine'
    ports:
      - '18080:8080'
      - '50000:50000'
    volumes: ['jenkins:/var/jenkins_home']
    networks:
      main:
        aliases: ['jenkins.daggerok.com']
    restart: always

volumes:
  postgres:
  gogs:
  jenkins:

networks:
  main:
----

.start everything:
[source,bash]
----
docker-compose up
----

.copy jenkins initial administration password from terminal (826524f963304870bea53ce9ccafead5):
[source,bash]
----
jenkins_1   | *************************************************************
jenkins_1   | *************************************************************
jenkins_1   | *************************************************************
jenkins_1   |
jenkins_1   | Jenkins initial setup is required. An admin user has been created and a password generated.
jenkins_1   | Please use the following password to proceed to installation:
jenkins_1   |
jenkins_1   | 826524f963304870bea53ce9ccafead5
jenkins_1   |
jenkins_1   | This may also be found at: /var/jenkins_home/secrets/initialAdminPassword
jenkins_1   |
jenkins_1   | *************************************************************
jenkins_1   | *************************************************************
jenkins_1   | *************************************************************
----

go to http://jenkins.daggerok.com:18080/ paste it here and click on install recommended plugins...

while jenkins doing it's job, go to http://gogs.daggerok.com:13000/

install with postgres database:

  host = postgres.daggerok.com
  port = 5432
  db name = gogs
  db user = gogs
  db user password = gogs

setup correct public url, like http://gogs.daggerok.com:13000/

create gogs admin user

back to jenkins and create jenkins admin user after it finish intalling plugins

.when you done with development, just stop docker-compos
[source,bash]
----
docker-compose down
----

so later you can continue with same command from first point

links:

// . link:https://docs.gitlab.com/ce/[Gitlab CE]
// . link:https://docs.gitlab.com/omnibus/docker/#install-gitlab-using-docker-compose[Install Gitlab]
. link:https://hub.docker.com/_/postgres/[Install Postgres]
. link:https://github.com/gogs/gogs/tree/master/docker/[Install GoGs]
. link:https://github.com/jenkinsci/docker/[Install Jenkins]
. link:https://jenkins.io/[Jenkins]
